---
# Handlers for RabbitMQ
- name: restart rabbitmq-server
  service: name=rabbitmq-server state=restarted
  become: true

- name: start rabbitmq-server
  service: name=rabbitmq-server state=started
  become: true

- name: stop rabbitmq-server
  service: name=rabbitmq-server state=stopped
  become: true
